services:
  - type: web
    name: supply-chain-assistant
    runtime: python
    buildCommand: pip install -r backend/requirements.txt   # ←←← YE CHANGE KAR
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    
  - type: web
    name: supply-chain-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://supply-chain-assistant-4jy2.onrender.com/api
